/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete.grafico;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import paquete.clases.GestionVuelos;
import paquete.clases.Nodo;
import paquete.clases.Pasajero;
import paquete.clases.Vuelo;

/**
 *
 * @author Leonardo
 */
public class UIVuelos extends javax.swing.JFrame {

    /**
     * Creates new form UIVuelos
     */
    GestionVuelos objGE;
    DefaultTableModel modelo;
    DefaultTableModel modeloVuelos;
    
    public UIVuelos() {
        initComponents();
        setIcon();
        objGE = new GestionVuelos();
        
        //Inicializar modelo
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("DNI");
        modelo.addColumn("Edad");
        PassengerTable.setModel(modelo);
        
        //Inicializar modelo tabla de vuelos
        modeloVuelos = new DefaultTableModel();
        modeloVuelos.addColumn("Número de vuelo");
        modeloVuelos.addColumn("Destino");
        modeloVuelos.addColumn("Asientos disponibles");
        FlightTable.setModel(modeloVuelos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddPassengerPanel = new javax.swing.JPanel();
        SelectFlightLabel = new javax.swing.JLabel();
        FlightListComboBox = new javax.swing.JComboBox<>();
        PassengerNameLabel = new javax.swing.JLabel();
        PassengerNameTextField = new javax.swing.JTextField();
        PassengerDNILabel = new javax.swing.JLabel();
        PassengerDNITextField = new javax.swing.JTextField();
        AddPassengerButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightInfoTextPane = new javax.swing.JTextPane();
        FlightInfoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PassengerNameLabel1 = new javax.swing.JLabel();
        PassengerDNIDeleteTextField = new javax.swing.JTextField();
        DeletePassengerButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        DeleteFlightButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FlightNameLabel = new javax.swing.JLabel();
        FlightSeatsLabel = new javax.swing.JLabel();
        CreateFlightButton = new javax.swing.JButton();
        FlightNumberTextField = new javax.swing.JTextField();
        FlightSeatsNumberComboBox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        FlightDestinationLabel = new javax.swing.JLabel();
        FlightDestinationTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        SortFlightButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        PassengerTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de reserva de vuelos");
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddPassengerPanel.setBackground(new java.awt.Color(225, 225, 225));
        AddPassengerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelectFlightLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        SelectFlightLabel.setText("Paso 2. Seleccione un vuelo");
        AddPassengerPanel.add(SelectFlightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        FlightListComboBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        FlightListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir vuelo" }));
        FlightListComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                FlightListComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        FlightListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightListComboBoxActionPerformed(evt);
            }
        });
        AddPassengerPanel.add(FlightListComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        PassengerNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PassengerNameLabel.setText("Ingrese DNI del pasajero a eliminar:");
        AddPassengerPanel.add(PassengerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        PassengerNameTextField.setBackground(new java.awt.Color(225, 225, 225));
        PassengerNameTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PassengerNameTextField.setForeground(new java.awt.Color(102, 102, 102));
        PassengerNameTextField.setText("Ingrese nombre");
        PassengerNameTextField.setBorder(null);
        PassengerNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassengerNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassengerNameTextFieldFocusLost(evt);
            }
        });
        AddPassengerPanel.add(PassengerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 174, -1));

        PassengerDNILabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PassengerDNILabel.setText("DNI del pasajero:");
        AddPassengerPanel.add(PassengerDNILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        PassengerDNITextField.setBackground(new java.awt.Color(225, 225, 225));
        PassengerDNITextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PassengerDNITextField.setForeground(new java.awt.Color(102, 102, 102));
        PassengerDNITextField.setText("Ingrese DNI");
        PassengerDNITextField.setBorder(null);
        PassengerDNITextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassengerDNITextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassengerDNITextFieldFocusLost(evt);
            }
        });
        AddPassengerPanel.add(PassengerDNITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 174, -1));

        AddPassengerButton.setBackground(new java.awt.Color(255, 255, 255));
        AddPassengerButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        AddPassengerButton.setText("Añadir pasajero");
        AddPassengerButton.setBorderPainted(false);
        AddPassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassengerButtonActionPerformed(evt);
            }
        });
        AddPassengerPanel.add(AddPassengerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 136, -1));

        jScrollPane2.setBackground(new java.awt.Color(232, 228, 224));

        FlightInfoTextPane.setEditable(false);
        FlightInfoTextPane.setBackground(new java.awt.Color(224, 224, 224));
        FlightInfoTextPane.setBorder(null);
        FlightInfoTextPane.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(FlightInfoTextPane);

        AddPassengerPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 50));

        FlightInfoLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        FlightInfoLabel.setText("Información del vuelo:");
        AddPassengerPanel.add(FlightInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        AddPassengerPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 180, 10));

        PassengerNameLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PassengerNameLabel1.setText("Nombre del pasajero:");
        AddPassengerPanel.add(PassengerNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        PassengerDNIDeleteTextField.setBackground(new java.awt.Color(225, 225, 225));
        PassengerDNIDeleteTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PassengerDNIDeleteTextField.setForeground(new java.awt.Color(102, 102, 102));
        PassengerDNIDeleteTextField.setText("Ingrese DNI");
        PassengerDNIDeleteTextField.setBorder(null);
        PassengerDNIDeleteTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PassengerDNIDeleteTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassengerDNIDeleteTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassengerDNIDeleteTextFieldFocusLost(evt);
            }
        });
        AddPassengerPanel.add(PassengerDNIDeleteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 180, -1));

        DeletePassengerButton.setBackground(new java.awt.Color(255, 255, 255));
        DeletePassengerButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DeletePassengerButton.setText("Eliminar pasajero");
        DeletePassengerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletePassengerButtonActionPerformed(evt);
            }
        });
        AddPassengerPanel.add(DeletePassengerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Ver pasajero con mayor edad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddPassengerPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        AddPassengerPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 180, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        AddPassengerPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 180, 10));

        DeleteFlightButton.setBackground(new java.awt.Color(255, 255, 255));
        DeleteFlightButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DeleteFlightButton.setText("Presionar para eliminar vuelo");
        DeleteFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteFlightButtonActionPerformed(evt);
            }
        });
        AddPassengerPanel.add(DeleteFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Paso 3. Gestione sus vuelos");
        AddPassengerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        getContentPane().add(AddPassengerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 270, 510));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlightNameLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        FlightNameLabel.setText("Número de vuelo:");
        jPanel1.add(FlightNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 145, -1));

        FlightSeatsLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        FlightSeatsLabel.setText("Número de asientos:");
        jPanel1.add(FlightSeatsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        CreateFlightButton.setBackground(new java.awt.Color(255, 255, 255));
        CreateFlightButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CreateFlightButton.setText("Crear vuelo");
        CreateFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateFlightButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 120, -1));

        FlightNumberTextField.setBackground(new java.awt.Color(102, 204, 255));
        FlightNumberTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FlightNumberTextField.setForeground(new java.awt.Color(102, 102, 102));
        FlightNumberTextField.setText("Ingrese número");
        FlightNumberTextField.setBorder(null);
        FlightNumberTextField.setCaretColor(new java.awt.Color(51, 51, 51));
        FlightNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FlightNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FlightNumberTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(FlightNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, -1));

        FlightSeatsNumberComboBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        FlightSeatsNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "150", "200" }));
        jPanel1.add(FlightSeatsNumberComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 10));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Paso 1. Cree sus vuelos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        FlightDestinationLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        FlightDestinationLabel.setText("Destino del vuelo:");
        jPanel1.add(FlightDestinationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        FlightDestinationTextField.setBackground(new java.awt.Color(102, 204, 255));
        FlightDestinationTextField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FlightDestinationTextField.setForeground(new java.awt.Color(102, 102, 102));
        FlightDestinationTextField.setText("Ingrese destino");
        FlightDestinationTextField.setBorder(null);
        FlightDestinationTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FlightDestinationTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FlightDestinationTextFieldFocusLost(evt);
            }
        });
        jPanel1.add(FlightDestinationTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 10));

        SortFlightButton.setBackground(new java.awt.Color(255, 255, 255));
        SortFlightButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SortFlightButton.setText("Ordenar listado por destino");
        SortFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortFlightButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SortFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 310));

        PassengerTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        PassengerTable.setForeground(new java.awt.Color(51, 51, 51));
        PassengerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        PassengerTable.setGridColor(new java.awt.Color(255, 255, 255));
        PassengerTable.setRowHeight(20);
        PassengerTable.setSelectionBackground(new java.awt.Color(225, 225, 225));
        jScrollPane3.setViewportView(PassengerTable);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 800, 510));

        FlightTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        FlightTable.setForeground(new java.awt.Color(51, 51, 51));
        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(FlightTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 800, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateFlightButtonActionPerformed
        try {
            int numVuelo = Integer.parseInt(FlightNumberTextField.getText());
            int numAsientos = Integer.parseInt((String) FlightSeatsNumberComboBox.getSelectedItem());
            String destino = FlightDestinationTextField.getText();
            if ("Ingrese destino".equals(destino)) {
                JOptionPane.showMessageDialog(null, "Ingrese destino válido, por favor.");
                //Limpiar campos
                FlightNumberTextField.setText("Ingrese número");
                FlightSeatsNumberComboBox.setSelectedIndex(0);
                FlightDestinationTextField.setText("Ingrese destino");
            } else {
                Vuelo objVuelo = new Vuelo(numVuelo, numAsientos, destino);

                //Añadir vuelo a FlightListComboBox:
                if (objGE.agregarVuelo(objVuelo)) {
                    FlightListComboBox.addItem(FlightNumberTextField.getText());
                }

                actualizarTablaVuelos();

                //Limpiar campos
                FlightNumberTextField.setText("Ingrese número");
                FlightSeatsNumberComboBox.setSelectedIndex(0);
                FlightDestinationTextField.setText("Ingrese destino");

                objGE.verInfo();
            }            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese número de vuelo válido, por favor.");
            //Limpiar campos
            FlightNumberTextField.setText("Ingrese número");
            FlightSeatsNumberComboBox.setSelectedIndex(0);
            FlightDestinationTextField.setText("Ingrese destino");
        }
        
    }//GEN-LAST:event_CreateFlightButtonActionPerformed

    private void AddPassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassengerButtonActionPerformed
        try {
            int vueloSeleccionado = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
            int pos = objGE.busquedaS(vueloSeleccionado);
            String nombre = PassengerNameTextField.getText();
            long dni = Long.decode(PassengerDNITextField.getText());
            Pasajero objPasajero = new Pasajero(nombre, dni);
            objGE.getArreglo()[pos].agregarPasajeroAlVuelo(objPasajero);
            
            System.out.println(objGE.getArreglo()[pos].obeneterInfoVuelo());
            
            actualizarTabla();
            actualizarTablaVuelos();
            
            String cad = objGE.getArreglo()[pos].obeneterInfoVueloSinPasajeros();
            FlightInfoTextPane.setText(cad);
            System.out.println("--------------");
            
            //Limpiar campos
            PassengerDNITextField.setText("Ingrese DNI");
            PassengerNameTextField.setText("Ingrese nombre");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores correctos, por favor.");
            
            //Limpiar campos
            PassengerDNITextField.setText("Ingrese DNI");
            PassengerNameTextField.setText("Ingrese nombre");
        }

    }//GEN-LAST:event_AddPassengerButtonActionPerformed

    private void FlightListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightListComboBoxActionPerformed
        try {
            int vueloSeleccionado = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
            int pos = objGE.busquedaS(vueloSeleccionado);
            String cad = objGE.getArreglo()[pos].obeneterInfoVueloSinPasajeros();
            FlightInfoTextPane.setText(cad);
            actualizarTabla();
        } catch (Exception e) {
            FlightInfoTextPane.setText("");
        }        
    }//GEN-LAST:event_FlightListComboBoxActionPerformed

    private void FlightListComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_FlightListComboBoxPopupMenuWillBecomeVisible
        PassengerNameTextField.setText("Ingrese nombre");
        PassengerDNITextField.setText("Ingrese DNI");
        PassengerDNIDeleteTextField.setText("Ingrese DNI");
    }//GEN-LAST:event_FlightListComboBoxPopupMenuWillBecomeVisible

    private void DeletePassengerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletePassengerButtonActionPerformed
        try {
            long dni = Long.decode(PassengerDNIDeleteTextField.getText());
            int vueloSeleccionado = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
            int pos = objGE.busquedaS(vueloSeleccionado);

            objGE.getArreglo()[pos].eliminarPasajeroDelVuelo(dni);
            
            actualizarTabla();
            actualizarTablaVuelos();

            System.out.println(objGE.getArreglo()[pos].obeneterInfoVuelo());

            String cad = objGE.getArreglo()[pos].obeneterInfoVueloSinPasajeros();
            FlightInfoTextPane.setText(cad);
            System.out.println("--------------");

            //Limpiar campos
            PassengerDNIDeleteTextField.setText("Ingrese DNI");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese valores correctos, por favor.");
            //Limpiar campos
            PassengerDNIDeleteTextField.setText("Ingrese DNI");
        }
    }//GEN-LAST:event_DeletePassengerButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int vueloSeleccionado = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
            int pos = objGE.busquedaS(vueloSeleccionado);
            objGE.getArreglo()[pos].verMayorEdadEnVuelo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione vuelo, por favor.");
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteFlightButtonActionPerformed
        // TODO add your handling code here:
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "¿Eliminar vuelo?","Advertencia",dialogButton);
            
            if (dialogResult == JOptionPane.YES_OPTION) {
                int numVuelo = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
                objGE.eliminarConReferencia(numVuelo);

                int index = FlightListComboBox.getSelectedIndex();

                FlightListComboBox.setSelectedIndex(0);
                FlightListComboBox.removeItemAt(index);
                modelo.setRowCount(0);
                
                actualizarTablaVuelos();
            }            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione vuelo, por favor.");
        }
    }//GEN-LAST:event_DeleteFlightButtonActionPerformed

    private void FlightNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FlightNumberTextFieldFocusGained
        if ("Ingrese número".equals(FlightNumberTextField.getText())) { 
            FlightNumberTextField.setText("");
        }
    }//GEN-LAST:event_FlightNumberTextFieldFocusGained

    private void FlightNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FlightNumberTextFieldFocusLost
        if ("".equals(FlightNumberTextField.getText())) { 
            FlightNumberTextField.setText("Ingrese número");
        }
    }//GEN-LAST:event_FlightNumberTextFieldFocusLost

    private void PassengerNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerNameTextFieldFocusGained
        if ("Ingrese nombre".equals(PassengerNameTextField.getText())) { 
            PassengerNameTextField.setText("");
        }
    }//GEN-LAST:event_PassengerNameTextFieldFocusGained

    private void PassengerNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerNameTextFieldFocusLost
        if ("".equals(PassengerNameTextField.getText())) { 
            PassengerNameTextField.setText("Ingrese nombre");
        }
    }//GEN-LAST:event_PassengerNameTextFieldFocusLost

    private void PassengerDNITextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerDNITextFieldFocusGained
        if ("Ingrese DNI".equals(PassengerDNITextField.getText())) { 
            PassengerDNITextField.setText("");
        }
    }//GEN-LAST:event_PassengerDNITextFieldFocusGained

    private void PassengerDNITextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerDNITextFieldFocusLost
        if ("".equals(PassengerDNITextField.getText())) { 
            PassengerDNITextField.setText("Ingrese DNI");
        }
    }//GEN-LAST:event_PassengerDNITextFieldFocusLost

    private void PassengerDNIDeleteTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerDNIDeleteTextFieldFocusGained
        if ("Ingrese DNI".equals(PassengerDNIDeleteTextField.getText())) { 
            PassengerDNIDeleteTextField.setText("");
        }
    }//GEN-LAST:event_PassengerDNIDeleteTextFieldFocusGained

    private void PassengerDNIDeleteTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassengerDNIDeleteTextFieldFocusLost
        if ("".equals(PassengerDNIDeleteTextField.getText())) { 
            PassengerDNIDeleteTextField.setText("Ingrese DNI");
        }
    }//GEN-LAST:event_PassengerDNIDeleteTextFieldFocusLost

    private void FlightDestinationTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FlightDestinationTextFieldFocusGained
        // TODO add your handling code here:
        if ("Ingrese destino".equals(FlightDestinationTextField.getText())) { 
            FlightDestinationTextField.setText("");
        }
    }//GEN-LAST:event_FlightDestinationTextFieldFocusGained

    private void FlightDestinationTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FlightDestinationTextFieldFocusLost
        // TODO add your handling code here:
        if ("".equals(FlightDestinationTextField.getText())) { 
            FlightDestinationTextField.setText("Ingrese destino");
        }
    }//GEN-LAST:event_FlightDestinationTextFieldFocusLost

    private void SortFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortFlightButtonActionPerformed
        // TODO add your handling code here:
        ordenarVuelos();
    }//GEN-LAST:event_SortFlightButtonActionPerformed
    
    private void actualizarTabla() {
        try {
            int vueloSeleccionado = Integer.parseInt((String) FlightListComboBox.getSelectedItem());
            modelo.setRowCount(0);
            int pos = objGE.busquedaS(vueloSeleccionado);
            String dato[] = new String[3];
            Nodo<Pasajero> ptr = objGE.getArreglo()[pos].getListaPasajeros().getL();
            while(ptr!=null) {
                dato[0] = ptr.getInfo().getNombre();
                dato[1] = String.valueOf(ptr.getInfo().getDni());
                dato[2] = String.valueOf(ptr.getInfo().getEdad());
                modelo.addRow(dato);
                ptr = ptr.getSiguiente();
            }            
        } catch (Exception e) {
        }
    }
    
    private void actualizarTablaVuelos() {
        try {
            modeloVuelos.setRowCount(0);
            String dato[] = new String[3];
            Vuelo[] arreglo = objGE.getArreglo();
            for (int i = 0; i < objGE.getCantidadVuelos(); i++) {
                System.out.println(arreglo[i].getDestino());
                dato[0] = "N" + String.valueOf(arreglo[i].getNumVuelo());
                dato[1] = arreglo[i].getDestino();
                dato[2] = String.valueOf(arreglo[i].getNumAsientos());
                modeloVuelos.addRow(dato);
            }
            
        } catch (Exception e) {
        }
    }
    
    private void ordenarVuelos() {
        try {
            modeloVuelos.setRowCount(0);
            String dato[] = new String[3];
            Vuelo[] arreglo = objGE.ordnearPorDestino();
            for (int i = 0; i < objGE.getCantidadVuelos(); i++) {
                dato[0] = "N" + String.valueOf(arreglo[i].getNumVuelo());
                dato[1] = arreglo[i].getDestino();
                dato[2] = String.valueOf(arreglo[i].getNumAsientos());
                modeloVuelos.addRow(dato);
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPassengerButton;
    private javax.swing.JPanel AddPassengerPanel;
    private javax.swing.JButton CreateFlightButton;
    private javax.swing.JButton DeleteFlightButton;
    private javax.swing.JButton DeletePassengerButton;
    private javax.swing.JLabel FlightDestinationLabel;
    private javax.swing.JTextField FlightDestinationTextField;
    private javax.swing.JLabel FlightInfoLabel;
    private javax.swing.JTextPane FlightInfoTextPane;
    private javax.swing.JComboBox<String> FlightListComboBox;
    private javax.swing.JLabel FlightNameLabel;
    private javax.swing.JTextField FlightNumberTextField;
    private javax.swing.JLabel FlightSeatsLabel;
    private javax.swing.JComboBox<String> FlightSeatsNumberComboBox;
    private javax.swing.JTable FlightTable;
    private javax.swing.JTextField PassengerDNIDeleteTextField;
    private javax.swing.JLabel PassengerDNILabel;
    private javax.swing.JTextField PassengerDNITextField;
    private javax.swing.JLabel PassengerNameLabel;
    private javax.swing.JLabel PassengerNameLabel1;
    private javax.swing.JTextField PassengerNameTextField;
    private javax.swing.JTable PassengerTable;
    private javax.swing.JLabel SelectFlightLabel;
    private javax.swing.JButton SortFlightButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("59919.png")));
    }
}
